-- ============================================================
-- Symbio-Exchange Oracle Schema + PL/SQL Objects
-- Purpose: DBMS-course compliant backend objects using PL/SQL
-- Includes: tables, constraints, function, cursor logic, procedures, trigger
-- ============================================================

-- Clean-up (safe to rerun in SQL*Plus / SQLcl)
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_offer_decisions_updated_at'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_respond_offer_decision'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_create_offer_decision'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_pair_criteria_match'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_offer_hazard_count'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE offer_decisions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE process_capabilities CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE hazard_matrix CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE acceptance_criteria CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE batch_composition CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE listings CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE chemicals CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- Core Tables
-- ============================================================
CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(120) NOT NULL,
  email         VARCHAR2(160) NOT NULL UNIQUE,
  password_hash VARCHAR2(300) NOT NULL,
  industry_type VARCHAR2(80),
  location      VARCHAR2(120),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE chemicals (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR2(40) NOT NULL UNIQUE,
  name         VARCHAR2(120) NOT NULL,
  hazard_level VARCHAR2(10) DEFAULT 'LOW' NOT NULL,
  CONSTRAINT chk_chem_hazard_level CHECK (hazard_level IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE listings (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       NUMBER NOT NULL,
  type          VARCHAR2(10) NOT NULL,
  material_name VARCHAR2(180) NOT NULL,
  quantity_tons NUMBER(12, 2) NOT NULL,
  status        VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_listing_type CHECK (type IN ('OFFER', 'DEMAND')),
  CONSTRAINT chk_listing_status CHECK (status IN ('ACTIVE', 'CLOSED', 'CANCELLED')),
  CONSTRAINT fk_listings_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE batch_composition (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id    NUMBER NOT NULL,
  chem_id       NUMBER NOT NULL,
  percentage    NUMBER(6, 2) NOT NULL,
  CONSTRAINT chk_batch_percentage CHECK (percentage >= 0 AND percentage <= 100),
  CONSTRAINT uq_listing_chem UNIQUE (listing_id, chem_id),
  CONSTRAINT fk_batch_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
  CONSTRAINT fk_batch_chemical FOREIGN KEY (chem_id) REFERENCES chemicals(id)
);

CREATE TABLE acceptance_criteria (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id     NUMBER NOT NULL,
  chem_id        NUMBER NOT NULL,
  min_percentage NUMBER(6,2),
  max_percentage NUMBER(6,2),
  CONSTRAINT chk_criteria_range CHECK (
    (min_percentage IS NULL OR (min_percentage >= 0 AND min_percentage <= 100))
    AND (max_percentage IS NULL OR (max_percentage >= 0 AND max_percentage <= 100))
    AND (min_percentage IS NULL OR max_percentage IS NULL OR min_percentage <= max_percentage)
  ),
  CONSTRAINT uq_criteria_listing_chem UNIQUE (listing_id, chem_id),
  CONSTRAINT fk_criteria_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
  CONSTRAINT fk_criteria_chemical FOREIGN KEY (chem_id) REFERENCES chemicals(id)
);

CREATE TABLE hazard_matrix (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chem_id_1       NUMBER NOT NULL,
  chem_id_2       NUMBER NOT NULL,
  is_incompatible NUMBER(1) DEFAULT 1 NOT NULL,
  notes           VARCHAR2(250),
  CONSTRAINT chk_hazard_incompat CHECK (is_incompatible IN (0,1)),
  CONSTRAINT uq_hazard_pair UNIQUE (chem_id_1, chem_id_2),
  CONSTRAINT fk_hazard_chem_1 FOREIGN KEY (chem_id_1) REFERENCES chemicals(id),
  CONSTRAINT fk_hazard_chem_2 FOREIGN KEY (chem_id_2) REFERENCES chemicals(id)
);

CREATE TABLE process_capabilities (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  processor_id          NUMBER NOT NULL,
  input_chem_id         NUMBER NOT NULL,
  output_chem_id        NUMBER NOT NULL,
  conversion_efficiency NUMBER(5,2) NOT NULL,
  CONSTRAINT chk_efficiency CHECK (conversion_efficiency > 0 AND conversion_efficiency <= 100),
  CONSTRAINT fk_proc_user FOREIGN KEY (processor_id) REFERENCES users(id),
  CONSTRAINT fk_proc_input FOREIGN KEY (input_chem_id) REFERENCES chemicals(id),
  CONSTRAINT fk_proc_output FOREIGN KEY (output_chem_id) REFERENCES chemicals(id)
);

CREATE TABLE offer_decisions (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_listing_id  NUMBER NOT NULL,
  demand_listing_id NUMBER NOT NULL,
  seller_user_id    NUMBER NOT NULL,
  buyer_user_id     NUMBER NOT NULL,
  seller_decision   VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
  buyer_decision    VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
  final_status      VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_seller_decision CHECK (seller_decision IN ('PENDING', 'ACCEPTED', 'REJECTED')),
  CONSTRAINT chk_buyer_decision CHECK (buyer_decision IN ('PENDING', 'ACCEPTED', 'REJECTED')),
  CONSTRAINT chk_final_status CHECK (final_status IN ('OPEN', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
  CONSTRAINT uq_offer_demand_pair UNIQUE (offer_listing_id, demand_listing_id),
  CONSTRAINT fk_offer_dec_offer FOREIGN KEY (offer_listing_id) REFERENCES listings(id) ON DELETE CASCADE,
  CONSTRAINT fk_offer_dec_demand FOREIGN KEY (demand_listing_id) REFERENCES listings(id) ON DELETE CASCADE,
  CONSTRAINT fk_offer_dec_seller FOREIGN KEY (seller_user_id) REFERENCES users(id),
  CONSTRAINT fk_offer_dec_buyer FOREIGN KEY (buyer_user_id) REFERENCES users(id)
);

CREATE INDEX idx_listings_type_status ON listings(type, status);
CREATE INDEX idx_batch_listing ON batch_composition(listing_id);
CREATE INDEX idx_criteria_listing ON acceptance_criteria(listing_id);
CREATE INDEX idx_decision_offer ON offer_decisions(offer_listing_id);
CREATE INDEX idx_decision_demand ON offer_decisions(demand_listing_id);
CREATE INDEX idx_decision_status ON offer_decisions(final_status);

-- ============================================================
-- Trigger Requirement: Auto-update timestamp
-- ============================================================
CREATE OR REPLACE TRIGGER trg_offer_decisions_updated_at
BEFORE UPDATE ON offer_decisions
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- ============================================================
-- Function Requirement 1: Hazard count for an OFFER listing
-- ============================================================
CREATE OR REPLACE FUNCTION fn_offer_hazard_count (
  p_offer_listing_id IN NUMBER
) RETURN NUMBER
IS
  v_cnt NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO v_cnt
  FROM batch_composition mc1
  JOIN batch_composition mc2
    ON mc1.listing_id = mc2.listing_id
   AND mc1.chem_id < mc2.chem_id
  JOIN hazard_matrix hm
    ON hm.chem_id_1 = mc1.chem_id
   AND hm.chem_id_2 = mc2.chem_id
   AND hm.is_incompatible = 1
  WHERE mc1.listing_id = p_offer_listing_id;

  RETURN NVL(v_cnt, 0);
END;
/

-- ============================================================
-- Function Requirement 2: Pair compatibility using explicit CURSOR
-- Returns 1 when OFFER meets all DEMAND criteria, else 0
-- ============================================================
CREATE OR REPLACE FUNCTION fn_pair_criteria_match (
  p_offer_listing_id  IN NUMBER,
  p_demand_listing_id IN NUMBER
) RETURN NUMBER
IS
  CURSOR cur_criteria IS
    SELECT chem_id, min_percentage, max_percentage
    FROM acceptance_criteria
    WHERE listing_id = p_demand_listing_id;

  v_offer_pct batch_composition.percentage%TYPE;
  v_chem_id   acceptance_criteria.chem_id%TYPE;
  v_min       acceptance_criteria.min_percentage%TYPE;
  v_max       acceptance_criteria.max_percentage%TYPE;
BEGIN
  OPEN cur_criteria;
  LOOP
    FETCH cur_criteria INTO v_chem_id, v_min, v_max;
    EXIT WHEN cur_criteria%NOTFOUND;

    BEGIN
      SELECT percentage
      INTO v_offer_pct
      FROM batch_composition
      WHERE listing_id = p_offer_listing_id
        AND chem_id = v_chem_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        CLOSE cur_criteria;
        RETURN 0;
    END;

    IF (v_min IS NOT NULL AND v_offer_pct < v_min)
       OR (v_max IS NOT NULL AND v_offer_pct > v_max)
    THEN
      CLOSE cur_criteria;
      RETURN 0;
    END IF;
  END LOOP;
  CLOSE cur_criteria;

  RETURN 1;
END;
/

-- ============================================================
-- Procedure Requirement 1: Initialize decision row
-- ============================================================
CREATE OR REPLACE PROCEDURE sp_create_offer_decision (
  p_offer_listing_id  IN NUMBER,
  p_demand_listing_id IN NUMBER
)
IS
  v_offer_owner  NUMBER;
  v_demand_owner NUMBER;
  v_exists       NUMBER;
BEGIN
  SELECT user_id INTO v_offer_owner
  FROM listings
  WHERE id = p_offer_listing_id
    AND type = 'OFFER'
    AND status = 'ACTIVE';

  SELECT user_id INTO v_demand_owner
  FROM listings
  WHERE id = p_demand_listing_id
    AND type = 'DEMAND'
    AND status = 'ACTIVE';

  IF fn_pair_criteria_match(p_offer_listing_id, p_demand_listing_id) = 0 THEN
    RAISE_APPLICATION_ERROR(-20010, 'Offer and demand pair is not criteria-compatible.');
  END IF;

  SELECT COUNT(*) INTO v_exists
  FROM offer_decisions
  WHERE offer_listing_id = p_offer_listing_id
    AND demand_listing_id = p_demand_listing_id;

  IF v_exists = 0 THEN
    INSERT INTO offer_decisions (
      offer_listing_id,
      demand_listing_id,
      seller_user_id,
      buyer_user_id,
      seller_decision,
      buyer_decision,
      final_status
    ) VALUES (
      p_offer_listing_id,
      p_demand_listing_id,
      v_offer_owner,
      v_demand_owner,
      'PENDING',
      'PENDING',
      'OPEN'
    );
  END IF;
END;
/

-- ============================================================
-- Procedure Requirement 2: Seller/Buyer response finalization
-- - both ACCEPTED => close both listings
-- - any REJECTED  => keep ACTIVE and mark REJECTED
-- ============================================================
CREATE OR REPLACE PROCEDURE sp_respond_offer_decision (
  p_offer_listing_id  IN NUMBER,
  p_demand_listing_id IN NUMBER,
  p_actor_user_id     IN NUMBER,
  p_decision          IN VARCHAR2
)
IS
  v_decision      VARCHAR2(10);
  v_row           offer_decisions%ROWTYPE;
  v_next_seller   VARCHAR2(10);
  v_next_buyer    VARCHAR2(10);
  v_next_status   VARCHAR2(10);
BEGIN
  v_decision := UPPER(TRIM(p_decision));

  IF v_decision NOT IN ('ACCEPTED', 'REJECTED') THEN
    RAISE_APPLICATION_ERROR(-20020, 'Decision must be ACCEPTED or REJECTED.');
  END IF;

  SELECT * INTO v_row
  FROM offer_decisions
  WHERE offer_listing_id = p_offer_listing_id
    AND demand_listing_id = p_demand_listing_id
  FOR UPDATE;

  IF v_row.final_status <> 'OPEN' THEN
    RAISE_APPLICATION_ERROR(-20021, 'Decision workflow is already finalized.');
  END IF;

  IF p_actor_user_id = v_row.seller_user_id THEN
    v_next_seller := v_decision;
    v_next_buyer := v_row.buyer_decision;
  ELSIF p_actor_user_id = v_row.buyer_user_id THEN
    v_next_seller := v_row.seller_decision;
    v_next_buyer := v_decision;
  ELSE
    RAISE_APPLICATION_ERROR(-20022, 'Actor is neither seller nor buyer for this pair.');
  END IF;

  IF v_next_seller = 'REJECTED' OR v_next_buyer = 'REJECTED' THEN
    v_next_status := 'REJECTED';
  ELSIF v_next_seller = 'ACCEPTED' AND v_next_buyer = 'ACCEPTED' THEN
    v_next_status := 'ACCEPTED';
  ELSE
    v_next_status := 'OPEN';
  END IF;

  UPDATE offer_decisions
  SET seller_decision = v_next_seller,
      buyer_decision = v_next_buyer,
      final_status = v_next_status
  WHERE id = v_row.id;

  IF v_next_status = 'ACCEPTED' THEN
    UPDATE listings
    SET status = 'CLOSED', updated_at = SYSTIMESTAMP
    WHERE id IN (p_offer_listing_id, p_demand_listing_id)
      AND status = 'ACTIVE';
  END IF;
END;
/

-- ============================================================
-- Seed minimum data to compile and demo objects
-- ============================================================
INSERT INTO users (name, email, password_hash, industry_type, location)
VALUES ('Tata Steel', 'waste.management@tatasteel.com', 'hash', 'Steel', 'Jamshedpur');

INSERT INTO users (name, email, password_hash, industry_type, location)
VALUES ('NTPC Dadri', 'ntpc.dadri@ntpc.co.in', 'hash', 'Power', 'Dadri');

INSERT INTO chemicals (code, name, hazard_level) VALUES ('SIO2', 'Silicon Dioxide', 'LOW');
INSERT INTO chemicals (code, name, hazard_level) VALUES ('AL2O3', 'Aluminium Oxide', 'LOW');
INSERT INTO chemicals (code, name, hazard_level) VALUES ('CAO', 'Calcium Oxide', 'MEDIUM');

INSERT INTO listings (user_id, type, material_name, quantity_tons, status)
VALUES (1, 'OFFER', 'Demo Recovered Fly Ash', 1500, 'ACTIVE');

INSERT INTO listings (user_id, type, material_name, quantity_tons, status)
VALUES (2, 'DEMAND', 'Demo Cement Feed', 1200, 'ACTIVE');

INSERT INTO batch_composition (listing_id, chem_id, percentage)
VALUES (1, 1, 55);
INSERT INTO batch_composition (listing_id, chem_id, percentage)
VALUES (1, 2, 22);
INSERT INTO batch_composition (listing_id, chem_id, percentage)
VALUES (1, 3, 4);

INSERT INTO acceptance_criteria (listing_id, chem_id, min_percentage, max_percentage)
VALUES (2, 1, 50, NULL);
INSERT INTO acceptance_criteria (listing_id, chem_id, min_percentage, max_percentage)
VALUES (2, 2, 15, NULL);
INSERT INTO acceptance_criteria (listing_id, chem_id, min_percentage, max_percentage)
VALUES (2, 3, NULL, 8);

COMMIT;
